version: '3.1'

services:
  mongo:
    image: mongo
    env_file: /.env
    container_name: mongodb
    ports:
      - "${MONGO_HOST_PORT}:27017"
    environment:
      MONGODB_DATABASE: ${name_db}
    volumes:
      - ${volume}:/data/db

volumes:
  mongo_data:
